services:
  tariffs-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ukraine_tariffs_fetcher
    env_file:
      - .env
    volumes:
      - ./assets:/app/assets
      - ./docs:/app/docs
      - ./config:/app/config
    networks:
      - deploy

  tariffs-deploy:
    build:
      context: .
      dockerfile: Dockerfile.wrangler
    image: deploy-tariffs
    container_name: deploy-tariffs
    working_dir: /workspace
    env_file:
      - .env
    volumes:
      - ./:/workspace
    networks:
      - deploy
    # Загрузка файла tariffs_ua.json напрямую в твой облачный Cloudflare R2 бакет "kommeter"
    command: >
      sh -c "wrangler r2 object put kommeter/ua/tariffs_ua.json --file=docs/tariffs_ua.json --remote"

networks:
  deploy:
    name: deploy
